
MY_GITHUB = "https://github.com/MagoOscuro91"
GITHUB_DESCARGAR = "https://github.com/MagoOscuro91/magic_mp3/archive/refs/heads/master.zip"
GITHUB_MAGICMP3 = "https://github.com/MagoOscuro91/magic_mp3"
COLACAO_DONAR = "https://www.paypal.com/donate/?hosted_button_id=43HYFYLLPPMAE"
TRAILER_MAGIC_YOUTUBE = "https://youtu.be/HVIHGh51iVQ"
TRABAJO_REFLEX_3H_PARTE_1 = "https://youtu.be/m7Ek-DWdOMs"
PAGINA_REPO = "https://github.com/MagoOscuro91/Magic_MP3_web"
TUTORIAL_MAGICMP3 = "https://youtu.be/oIgieqU4D9U"
MI_YOUTUBE = "https://www.youtube.com/channel/UCSreSq8_KxuME4T7aQlgQHw"
METAL_PYTHON = "https://open.spotify.com/playlist/0IuAVLwz2i6TzxiU3W9jK4?si=bcbe6c399cea4fb4"
SAVE_THEME_SPOTIFY = "https://open.spotify.com/playlist/14I3uYbp11Klu78Um0bsCc?si=f1b003bcfecd49b7"
REFLEX_URL = "https://reflex.dev/"
